name: Deployment
on:
  push:
    branches:
        - master
        - main
  pull_request:
    types:
      - opened
    
jobs:
  pull_request_opened:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -u check_pdb_instance.py
