name: Deployment
on:
  pull_request:
    types:
      - opened
    
jobs:
  pull_request_opened:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python check_pdb_instance.py
