name: Deployment
on:
  pull_request_review:
    types:
      - submitted
    
jobs:
  approved:
    if: github.event.review.state == "APPROVED"
    runs-on: ubunt-latest
    steps:
      - run: echo "This PR was approved"
